<a href="https://colab.research.google.com/github/wed0rex/Learn.Py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(3,3)

print(a)
print(b)

x=np.dot(a,b)
print(x)
x.transpose()

[[0.37427998 0.81701693 0.28525526]
 [0.00139645 0.99731314 0.91848349]
 [0.4622642  0.90927777 0.94915982]]
[[0.08460547 0.06964299 0.42358541]
 [0.2762627  0.06056775 0.53139867]
 [0.13197668 0.40258503 0.41291762]]
[[0.29502448 0.19039035 0.71048817]
 [0.39685697 0.43026996 0.90982041]
 [0.41557657 0.4693839  1.07092218]]


array([[0.29502448, 0.39685697, 0.41557657],
       [0.19039035, 0.43026996, 0.4693839 ],
       [0.71048817, 0.90982041, 1.07092218]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np
a=[[55,25,15], [30,44,2], [11,45,77]]
b=np.array(a)
print(b)
np.linalg.det(b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001