<a href="https://colab.research.google.com/github/wed0rex/Learn.Py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [11]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30',periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", ok.head())
print("\nTail:\n", ok.tail())
print("\nIndex:\n", ok.index)
print("\nColumns:\n", ok.columns)
print("\nValues:\n", ok.values)
print("\nStatistics:\n", ok.describe(include='all'))

Head:
                    A         B         C         D
2021-09-30 -0.829074  0.579963 -0.716656 -0.750506
2021-10-01 -0.346707  1.736948  0.707213 -1.612710
2021-10-02  0.200152  0.138903 -0.914101 -0.115653
2021-10-03 -0.364089 -0.570891  0.405609 -0.615999

Tail:
                    A         B         C         D
2021-09-30 -0.829074  0.579963 -0.716656 -0.750506
2021-10-01 -0.346707  1.736948  0.707213 -1.612710
2021-10-02  0.200152  0.138903 -0.914101 -0.115653
2021-10-03 -0.364089 -0.570891  0.405609 -0.615999

Index:
 DatetimeIndex(['2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03'], dtype='datetime64[ns]', freq='D')

Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')

Values:
 [[-0.82907356  0.57996261 -0.71665592 -0.75050627]
 [-0.34670725  1.73694796  0.70721263 -1.61270972]
 [ 0.20015227  0.13890252 -0.91410122 -0.11565311]
 [-0.36408864 -0.57089148  0.40560945 -0.6159988 ]]

Statistics:
               A         B         C         D
count  4.000000  4.000000  4.0

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [15]:
#please provide your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30',periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("\nTranspose\n", ok.transpose())
print("\nDescending Order\n", ok.sort_index(ascending=False))



Transpose
    2021-09-30  2021-10-01  2021-10-02  2021-10-03
A    0.475457   -0.843568    0.590779   -1.577487
B   -0.764720    1.066531   -1.626237    1.532715
C   -1.408058    0.473068    1.106828    1.687785
D   -0.630954    0.849001   -0.261398    0.286426

Descending Order
                    A         B         C         D
2021-10-03 -1.577487  1.532715  1.687785  0.286426
2021-10-02  0.590779 -1.626237  1.106828 -0.261398
2021-10-01 -0.843568  1.066531  0.473068  0.849001
2021-09-30  0.475457 -0.764720 -1.408058 -0.630954
